services:
  db:
    image: postgres:16
    container_name: laravel_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: foodadvisor
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/db:/docker-entrypoint-initdb.d
    networks:
      - foodadvisor_net

volumes:
  db_data:

networks:
  foodadvisor_net:
    external: true
